name: Build UnityDataTool

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [osx-arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Publish UnityDataTool (${{ matrix.arch }})
        run: >
          dotnet publish UnityDataTool
          -c Release
          -r ${{ matrix.arch }}
          -p:PublishSingleFile=true
          -p:UseAppHost=true
          -o publish/${{ matrix.arch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: UnityDataTool-${{ matrix.arch }}
          path: publish/${{ matrix.arch }}/UnityDataTool
